server:
  port: 8103
  context-path: /swms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka/

spring:
  application:
    name: lowering-swms
  aop:
    proxy-target-class: true
    
  thymeleaf:
    cache: false
    mode: HTML5
    
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/lowering-cloud?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
  rabbitmq:
    username: admin
    password: admin
    
security:
  sessions: stateless
  basic:
    enabled: false
  oauth2:
    sso:
      login-path: /login
    client:
      client-id: swms
      client-secret: swms
      access-token-uri: http://localhost:8102/sso/oauth/token
      user-authorization-uri: http://localhost:8102/sso/oauth/authorize
    resource:
      user-info-uri: http://localhost:8102/sso/api/me
    
    
    