server:
  port: 8102
  context-path: /authorize
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka/

spring:
  application:
    name: lowering-authorize

    
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: authorize
      client-secret: authorize
      access-token-uri: http://localhost:8102/authorize/oauth/token
      grant-type: client_credentials
      scope: server

    resource:
      filter-order: 3
      user-info-uri: http://localhost:8102/authorize/me
    
    
    