server:
  port: 8102
  context-path: /account

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka/

spring:
  application:
    name: lowering-account
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/lowering-cloud?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: account
      client-secret: account
      access-token-uri: http://localhost:8102/account/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:8102/account/me

