server:
  port: 0
  context-path: /account


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka/

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: account
      client-secret: account
      access-token-uri: http://localhost:8102/sso/oauth/token
      grant-type: client_credentials
      scope: server

    resource:
      user-info-uri: http://localhost:8102/sso/api/me

spring:
  application:
    name: lowering-account