server:
  port: 8103

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka/

spring:
  application:
    name: lowering-gateway
    
  thymeleaf:
    cache: false
    mode: HTML


zuul:
  ignored-services: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    lowering-account:
      path: /account/**
      url: http://localhost:8102
      strip-prefix: false
      sensitive-headers:


security:
  basic:
    enabled: false

  oauth2:
    client:
      client-id: gateway
      client-secret: gateway
      access-token-uri: http://localhost:8102/account/oauth/token
      scope: server

    resource:
      user-info-uri: http://localhost:8102/account/me

    
    
    