server:
  port: 8103

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka/

spring:
  application:
    name: lowering-gateway
  aop:
    proxy-target-class: true
    
  thymeleaf:
    cache: false
    mode: HTML5
  resources:
    static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      - classpath:/META-INF/resources/webjars/


zuul:
  ignored-services: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    lowering-account:
      path: /account/**
      strip-prefix: false
      sensitive-headers:
    lowering-authorize:
      path: /authorize/**
      strip-prefix: false
      sensitive-headers:

security:
  sessions: stateless
  basic:
    enabled: false
  oauth2:
    sso:
      login-path: /authorize/login
    client:
      client-id: ui
      client-secret: ui
      access-token-uri: http://localhost:8102/authorize/oauth/token
      user-authorization-uri: http://localhost:8102/authorize/oauth/authorize
      grant-type: authorization_code
      authentication-scheme: form
    resource:
      user-info-uri: http://localhost:8102/authorize/me

    
    
    