server:
  port: 8101
  
spring:
  application:
    name: lowering-registry
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka/
    fetch-registry: false
    register-with-eureka: false
    
security:
  sessions: stateless
  user:
    password: 123456
